#!/bin/bash

METRICS="one.hero
two.monkeys
three.rabbits
four.dogs
five.lions
six.elephants
seven.hippos
eight.rainbows
nine.cats
ten.guitars
eleven.maids
twelve.drummers
thirteen.luckycharms
fourteen.boxes
fifteen.houses
sixteen.desks
seventeen.cars
eighteen.windows
nineteen.dolls
twenty.dollars
twentyone.more
twentytwo.coffees
twentythree.visitors
twentyfour.buildings
twentyfive.blocks
twentysix.miles
twentyseven.marathons
twentyeight.marbles
twentynine.birds
thirty.rings
thirtyone.bells
thirtytwo.numbers"
